### PR TITLE
navbar hover and icon modified

### PR DESCRIPTION
**Pull request by aksh1**
navbar hover added
grow animation added to featuring icons

### CODE REVIEW

**Comment by chrisdev** [comment]
thanks @aksh1. Which issue does this refer too? If non listed, create a new issue for it and post a screen shot of the changes

**Comment by chrisdev** [comment]
@aksh1 noticed that you accidentally posted a duplicate file
 {{cookiecutter.repo_name}}/pages/static/css/app.scss~
I guess there was a conflict and this was created.
You can ``git rm`` and submit the PR again?

**Comment by chrisdev** [comment]
@aksh1 add this wildcard to the `.gitignore`

**Comment by aksh1** [comment]
@chrisdev done sir

**Comment by chrisdev** [comment]
@aksh1 well done 💃

**Pull request merged**
