### PR TITLE
Added Foundation scss, jquery, Normalise

### PR DESCRIPTION
**Pull request by Parbhat**

### CODE REVIEW

**Comment by chrisdev** [comment]
Ok for now!

**Comment by Parbhat** [comment]
@chrisdev  so I should uncomment the redis and elastic search from base settings

**Comment by chrisdev** [comment]
Hi
I've gotta script for this
I'm at lunch 
Will send a link ASAP. 
Regards
Chris

**Comment by Parbhat** [comment]
thanks @chrisdev  enjoy lunch :)

**Pull request merged**
